In [5]:
import numpy as np 
import pandas as pd
import os

In [22]:
ausjpy=pd.read_csv('/Users/ahmikvirani/Documents/backup/CS Fundamentals/PCP/Project/December_Data/AUDJPY-2025-12.csv', header=None)
ausnzd=pd.read_csv('/Users/ahmikvirani/Documents/backup/CS Fundamentals/PCP/Project/December_Data/AUDNZD-2025-12.csv', header=None)

In [23]:
ausnzd.head()

         0                      1        2        3
0  AUD/NZD  20251201 00:00:01.447  1.14205  1.14222
1  AUD/NZD  20251201 00:00:02.453  1.14202  1.14217
2  AUD/NZD  20251201 00:00:03.451  1.14202  1.14218
3  AUD/NZD  20251201 00:00:05.456  1.14205  1.14222
4  AUD/NZD  20251201 00:00:07.462  1.14207  1.14221

In [ ]:
ausjpy.head()

         0                      1        2        3
0  AUD/JPY  20251201 00:00:00.965  102.138  102.146
1  AUD/JPY  20251201 00:00:01.964  102.133  102.141
2  AUD/JPY  20251201 00:00:04.980  102.135  102.143
3  AUD/JPY  20251201 00:00:05.981  102.138  102.146
4  AUD/JPY  20251201 00:00:06.981  102.127  102.136

In [19]:
files = [f for f in os.listdir("./December_Data") if f != ".DS_Store"]
len(files)

19

In [21]:
files

['CHFJPY-2025-12.csv',
 'USDZAR-2025-12.csv',
 'EURUSD-2025-12.csv',
 'EURCHF-2025-12.csv',
 'GBPUSD-2025-12.csv',
 'CADJPY-2025-12.csv',
 'EURGBP-2025-12.csv',
 'GBPJPY-2025-12.csv',
 'EURJPY-2025-12.csv',
 'AUDNZD-2025-12.csv',
 'EURPLN-2025-12.csv',
 'NZDUSD-2025-12.csv',
 'USDMXN-2025-12.csv',
 'USDJPY-2025-12.csv',
 'AUDUSD-2025-12.csv',
 'USDCAD-2025-12.csv',
 'AUDJPY-2025-12.csv',
 'USDCHF-2025-12.csv',
 'USDTRY-2025-12.csv']

In [24]:
len(files)

19